games = [{'game_id': 663188, 'away_pitcher_note': '',
                            'winning_pitcher': 'Kyle Wright',
                            'winning_team': 'Atlanta Braves',
                                 'home_probable_pitcher': '',
                                   'game_date': '2022-08-10',
                                             'away_score': 8,
                                 'venue_name': 'Fenway Park',
                  'summary': '2022-08-10 - Atlanta Braves (8) @ Boston Red Sox (4) (Final)',
                  'home_rec': '54-58',
                  'inning_state': 'Bottom',
                  #'status': 'In Progress',
                  # 'status': 'Pre Game',
                  #'status' : 'Game Over',
                   'status': 'Final',
                  'home_score': 4,
                  'save_pitcher': None,
                  'Balls'   : 1,
                  'Strikes' : 0,
                  'Outs'     :2 ,
                  'game_num': 1, 'away_name': 'Atlanta Braves', 'game_datetime': '2022-08-10T23:10:00Z',
                  'doubleheader': 'N', 'losing_team': 'Boston Red Sox', 'home_pitcher_note': '',
                  'away_probable_pitcher': '', 'game_type': 'R', 'home_name': 'Boston Red Sox',
                  'away_id': 144, 'current_inning': 9, 'home_id': 111, 'losing_pitcher': 'Nick Pivetta',
                  'Batter': 'James Heehan',
                  'current_inning' : 7,
                  'venue_id': 3, 'away_rec': '66-46'}]
