""" NON PROD LOCAL TEST FILE """

# statuses = [ 'In Progress', 'Final', 'Pre Game', 'Game Over',  ]
# for x in statuses:

games = [
    {
        "game_id": 663188,
        "away_pitcher_note": "",
        "winning_pitcher": "Kyle Wright",
        "winning_team": "Atlanta Braves",
        "home_probable_pitcher": "",
        "game_date": "2022-08-10",
        "away_score": 8,
        "venue_name": "Fenway Park",
        "summary": "2022-08-10 - Atlanta Braves (8) @ Boston Red Sox (4) (Final)",
        "home_rec": "54-58",
        "inning_state": "Bottom",
        "status": "In Progress",
        # 'status': 'Pre Game',
        #'status' : 'Game Over',
        # 'status': 'Final',
        "home_score": 4,
        "save_pitcher": None,
        "Balls": 1,
        "Strikes": 0,
        "Outs": 2,
        "game_num": 1,
        "away_name": "Atlanta Braves",
        "game_datetime": "2022-08-10T23:10:00Z",
        "doubleheader": "N",
        "losing_team": "Boston Red Sox",
        "home_pitcher_note": "",
        "away_probable_pitcher": "",
        "game_type": "R",
        "home_name": "Boston Red Sox",
        "away_id": 121,
        "current_inning": 9,
        "home_id": 113,
        "losing_pitcher": "Nick Pivetta",
        "Batter": "James Heehan",
        "current_inning": 7,
        "venue_id": 3,
        "away_rec": "66-46",
    },
    {
        "game_id": 663188,
        "away_pitcher_note": "",
        "winning_pitcher": "Kyle Wright",
        "winning_team": "Atlanta Braves",
        "home_probable_pitcher": "",
        "game_date": "2022-08-10",
        "away_score": 8,
        "venue_name": "Fenway Park",
        "summary": "2022-08-10 - Atlanta Braves (8) @ Boston Red Sox (4) (Final)",
        "home_rec": "54-58",
        "inning_state": "Bottom",
        "status": "Final",
        "home_score": 4,
        "save_pitcher": None,
        "Balls": 1,
        "Strikes": 0,
        "Outs": 2,
        "game_num": 1,
        "away_name": "Atlanta Braves",
        "game_datetime": "2022-08-10T23:10:00Z",
        "doubleheader": "N",
        "losing_team": "Boston Red Sox",
        "home_pitcher_note": "",
        "away_probable_pitcher": "",
        "game_type": "R",
        "home_name": "Boston Red Sox",
        "away_id": 134,
        "current_inning": 9,
        "home_id": 113,
        "losing_pitcher": "Nick Pivetta",
        "Batter": "James Heehan",
        "current_inning": 7,
        "venue_id": 3,
        "away_rec": "66-46",
    },
    {
        "game_id": 663188,
        "away_pitcher_note": "",
        "winning_pitcher": "Kyle Wright",
        "winning_team": "Atlanta Braves",
        "home_probable_pitcher": "",
        "game_date": "2022-08-10",
        "away_score": 8,
        "venue_name": "Fenway Park",
        "summary": "2022-08-10 - Atlanta Braves (8) @ Boston Red Sox (4) (Final)",
        "home_rec": "54-58",
        "inning_state": "Bottom",
        "status": "Pre Game",
        "home_score": 4,
        "save_pitcher": None,
        "Balls": 1,
        "Strikes": 0,
        "Outs": 2,
        "game_num": 1,
        "away_name": "Atlanta Braves",
        "game_datetime": "2022-08-10T23:10:00Z",
        "doubleheader": "N",
        "losing_team": "Boston Red Sox",
        "home_pitcher_note": "",
        "away_probable_pitcher": "",
        "game_type": "R",
        "home_name": "Boston Red Sox",
        "away_id": 134,
        "current_inning": 9,
        "home_id": 113,
        "losing_pitcher": "Nick Pivetta",
        "Batter": "James Heehan",
        "current_inning": 7,
        "venue_id": 3,
        "away_rec": "66-46",
    },
    {
        "game_id": 663188,
        "away_pitcher_note": "",
        "winning_pitcher": "Kyle Wright",
        "winning_team": "Atlanta Braves",
        "home_probable_pitcher": "",
        "game_date": "2022-08-10",
        "away_score": 8,
        "venue_name": "Fenway Park",
        "summary": "2022-08-10 - Atlanta Braves (8) @ Boston Red Sox (4) (Final)",
        "home_rec": "54-58",
        "inning_state": "Bottom",
        "status": "Game Over",
        "home_score": 4,
        "save_pitcher": None,
        "Balls": 1,
        "Strikes": 0,
        "Outs": 2,
        "game_num": 1,
        "away_name": "Atlanta Braves",
        "game_datetime": "2022-08-10T23:10:00Z",
        "doubleheader": "N",
        "losing_team": "Boston Red Sox",
        "home_pitcher_note": "",
        "away_probable_pitcher": "",
        "game_type": "R",
        "home_name": "Boston Red Sox",
        "away_id": 134,
        "current_inning": 9,
        "home_id": 113,
        "losing_pitcher": "Nick Pivetta",
        "Batter": "James Heehan",
        "current_inning": 7,
        "venue_id": 3,
        "away_rec": "66-46",
    },
    {
        "doubleheader": "N",
        "away_pitcher_note": "",
        "game_date": "2023-04-17",
        "inning_state": "Top",
        "away_probable_pitcher": "",
        "home_rec": "8-8",
        "away_rec": "7-8",
        "game_num": 1,
        "game_datetime": "2023-04-17T15:10:00Z",
        "current_inning": 1,
        "game_type": "R",
        "away_score": 0,
        "away_name": "Los Angeles Angels",
        "summary": "2023-04-17 - Los Angeles Angels @ Boston Red Sox (Delayed Start: Rain)",
        "away_id": 108,
        "home_name": "Boston Red Sox",
        "status": "Delayed Start: Rain",
        "venue_id": 3,
        "venue_name": "Fenway Park",
        "home_probable_pitcher": "",
        "home_pitcher_note": "",
        "home_score": 0,
        "home_id": 111,
        "game_id": 718540,
    },
    {
        "doubleheader": "N",
        "away_pitcher_note": "",
        "game_date": "2023-04-17",
        "inning_state": "Top",
        "away_probable_pitcher": "",
        "home_rec": "8-8",
        "away_rec": "7-8",
        "game_num": 1,
        "game_datetime": "2023-04-17T15:10:00Z",
        "current_inning": 1,
        "game_type": "R",
        "away_score": 0,
        "away_name": "Los Angeles Angels",
        "summary": "2023-04-17 - Los Angeles Angels @ Boston Red Sox (Warmup)",
        "away_id": 108,
        "home_name": "Boston Red Sox",
        "status": "Warmup",
        "venue_id": 3,
        "venue_name": "Fenway Park",
        "home_probable_pitcher": "",
        "home_pitcher_note": "",
        "home_score": 0,
        "home_id": 111,
        "game_id": 718540,
    },
]
